### ISSUE TITLE
OpenSGX_loader needs prototype

### ISSUE THREAD

**Issue by ramsdell** [sslab-gatech/opensgx#11]
The function OpenSGX reeds a protocol, because otherwise, it is use as an int returning function, and truncates the higher bits of the returned address.

John

diff --git a/user/include/sgx-user.h b/user/include/sgx-user.h
index 7033ec1..f6f75c6 100644
--- a/user/include/sgx-user.h
+++ b/user/include/sgx-user.h
@@ -33,3 +33,5 @@ extern void exception_handler(void);
 
 extern void sgx_enter(tcs_t *tcs, void (*aep)());
 extern void sgx_resume(tcs_t *tcs, void (*aep)());
+
+extern void *OpenSGX_loader(char *binary, int size, long offset, int n_of_pages);

**Comment by johnmwshih** [comment]
https://github.com/sslab-gatech/opensgx/commit/ec008b153664e581b2738760562861a8b6e06256

Thanks!
