### ISSUE TITLE
Support for PolarSSL's net_* functions

### ISSUE THREAD

**Issue by jonhoo** [sslab-gatech/opensgx#12]
I noticed that some preliminary work has been done on making PolarSSL's (now named mbed TLS by the way) net_* functions work. For example, the code in `net.c` has been modified to use `sgx_memcpy` and `sgx_memset`. Are there any plans to extend this to support establishing TLS connections inside the enclave?

The modifications are likely to be relatively mechanical (e.g., changing `connect` to `sgx_connect`, `bind` to `sgx_bind`, etc.), but there will probably a lot of them. PolarSSL is modular enough that it may be possible to simply override handlers all over the place, but it would be very useful if OpenSGX provided this out-of-the-box!

**Comment by jonhoo** [comment]
In fact, looking at [a recent diff](https://github.com/sslab-gatech/opensgx/commit/e0d676ba4ce905cf3b5ef77b65a10215986e56ae#diff-8d87439bb8437c29946ba2e18df6b2c6L121) that removes a bunch of code, it seems like it is possible to access OpenSSL through OpenSGX. Is this documented anywhere?

**Comment by johnmwshih** [comment]
Yes we've ported OpenSSL and made some applications (e.g., Tor). We are currently working on making a more complete version. Should be released soon.

**Comment by johnmwshih** [comment]
Due to libc support, now we are able to support native openssl/polarssl library inside the enclave. Closing this issue!
