### ISSUE TITLE
make -j $(nproc) on Arch-Linux-64bit fails

### ISSUE THREAD

**Issue by m1ghtym0** [sslab-gatech/opensgx#16]
./configure-arch works fine
make -j $(nproc) gives the following error message:
make[1]: *** No rule to make target 'target-i386/crypto_helper.o', needed by 'qemu-x86_64'.  Stop.
make[1]: *** Waiting for unfinished jobs....
  CC    x86_64-linux-user/target-i386/seg_helper.o
Makefile:163: recipe for target 'subdir-x86_64-linux-user' failed
make: *** [subdir-x86_64-linux-user] Error 2

**Comment by johnmwshih** [comment]
Thanks for your report. Should work now.

https://github.com/sslab-gatech/opensgx/commit/6ef30634205ec70bdfe725d76329a500901464e3
