### ISSUE TITLE
gelf.h: No such file or directory

### ISSUE THREAD

**Issue by ramsdell** [sslab-gatech/opensgx#20]
On Ubuntu 14.04 LTS after a pull this morning.

When I run "make -C user", I get the error message: 

cc -g -Iinclude -Ishare/include -Wall -pedantic -Wno-unused-function -std=gnu11 -fno-stack-protector -fvisibility=hidden   -c -o sgx-loader.o sgx-loader.c
sgx-loader.c:36:18: fatal error: gelf.h: No such file or directory
 #include <gelf.h>
                  ^
compilation terminated.

When I went to install libelf, I was told it is obsolete.

John

**Comment by johnmwshih** [comment]
Could you check other package name like libelf-dev?

**Comment by ramsdell** [comment]
That's the fix.  It compiles after installing libelf-dev.  Please add this dependency to README.md.

Thanks.

**Comment by johnmwshih** [comment]
https://github.com/sslab-gatech/opensgx/commit/fc7affd002a9a5ee176c2b06753f65f33af202a6

**Comment by andrewkitaev** [comment]
> Could you check other package name like libelf-dev?

thank you)

**Comment by LamSut** [comment]
> Could you check other package name like libelf-dev?

thanks bro

**Comment by Albertchamberlain** [comment]
> libelf-dev


thanks

**Comment by RealaxER** [comment]
it run good

**Comment by mihna123** [comment]
> Could you check other package name like libelf-dev?


Thanks man

**Comment by Schweizliu** [comment]
That doesn't work for me,
The motherboard is MS1585, Ubuntu20.04, the system has installed this package including libncurses5-dev, libssl-dev, libelf-dev

**Comment by 238Ver** [comment]
Thx, it works for me

**Comment by oriongamesdev** [comment]
Works to me, 

apt-get install libelf-dev

**Comment by RaviHaravina-eaton** [comment]
Thank you, it worked for me too...
