### ISSUE TITLE
OpenSSL usage

### ISSUE THREAD

**Issue by Runingtime** [sslab-gatech/opensgx#32]
I want to use opensgx to develop an application that can encrypt messages. I’m wondering how i can compile OpenSSL and use it in an enclave. Can you please add this to your tutorial? 
Besides,i think it will be better if the tutorial includes  usages of all available user-level APIs.
Thank you!

**Comment by johnmwshih** [comment]
In short, you can just statically link the openssl library. You may find the information in user/Makefile.
