### ISSUE TITLE
Enclave entry and exit

### ISSUE THREAD

**Issue by Runingtime** [sslab-gatech/opensgx#38]
Hello,I meet with some difficulties about Enclave's entry and exit because I can't find the related interfaces.
For example,how can I switch to my enclave program to run when the main program is running?And how to leave the enclave to carry on the main program? 
Can you give me some guidance about the related interfaces?
Thanks a lot!

**Comment by johnmwshih** [comment]
You can use the sgx_enter (https://github.com/sslab-gatech/opensgx/blob/master/user/sgx-runtime.c#L85) and sgx_exit (https://github.com/sslab-gatech/opensgx/blob/master/user/demo/hello.c#L29) pair to switch between host program and enclave. Please check the demo example for more detail.
