### ISSUE TITLE
Remote-attestation example is non-functional

### ISSUE THREAD

**Issue by ahawad** [sslab-gatech/opensgx#44]
I have tried running the provided remote-attestation example, but it doesn't proceed to success; in fact, 
it seems that all three enclave programs "hang" after the call to malloc in the sgx-remote-attestation library. 

Removing the call to malloc and replacing the dynamic arrays with static ones leads to progress. However, the attestation fails providing the error "Mac mismatch" . 

When I tried to use printf to see what the values are of the calculated and provided MACs, garbage is output to the terminal. I am not entirely sure where things are going wrong, to be honest. Do you guys have any information on this issue/am I perhaps doing something wrong? 

In case it matters I am running openSGX in kubuntu and compiled it as per the tutorial file.

**Comment by ramsdell** [comment]
I discovered my setjmp missing problem disappears if I revert to commit 6cc1fe695b61bd34eed199402b8ea575a6fe49ed.  I suggest you try this commit and see what happens.

**Comment by ahawad** [comment]
Reverting to that commit has indeed fixed the issue thanks for the suggestion.
