### ISSUE TITLE
sgx-utils.c dump_sigstruct buffer not big enough

### ISSUE THREAD

**Issue by jethrogb** [sslab-gatech/opensgx#5]
The buffer allocated for snprintf in `dump_sigstruct` in sgx-utils.c is not big enough to hold the entire data structure. Q2 gets truncated by 204 bytes.

**Comment by johnmwshih** [comment]
Fixed on https://github.com/sslab-gatech/opensgx/commit/25a6e9ecc59e60e73802cc961fc097b20a5d4479
Thanks for your report.
