### ISSUE TITLE
Intra-attest Mac not match

### ISSUE THREAD

**Issue by Fr0stM0urne** [sslab-gatech/opensgx#61]
The intra-attest challenge in the tutorial pdf fails at mac match on ubuntu. Can anyone please tell how to fix this?

**Comment by BoujdadFz** [comment]
Hello,

I'm having same issue since days ago; could you resolve it? if yes, could you please tell how you did. Otherwise, if I get it work properly, I'll post it here. Thank you in advance

**Comment by Fr0stM0urne** [comment]
Did you run all of the commands correctly? I think there was a typo in the commands that was causing the error. Make sure to type the symbols in commands and not copy/paste them to terminal. The minus '-' symbol is copied incorrectly that leads to failure of execution of those commands.

**Comment by BoujdadFz** [comment]
thanks for the quick reply. Actually, I think so, because I'm having a failure at run time (I didn't copy/paste), it stops at the challenger 'sending report to target..' while it displays at the target side that there was fail. so you mean even like this, it's at the commands level?

**Comment by Fr0stM0urne** [comment]
Try this #44 revert to a previous version.

**Comment by BoujdadFz** [comment]
Yes, it worked at this version; thank you so much. I hope that I'm not missing big functionalities at this one :)
